"""ISO 14229-1 (UDS) identifiers used by the platform.

Only values defined by the standard are listed here. Manufacturer-specific identifiers (DIDs,
routines, DTC meanings) are never hardcoded: they come from versioned definition catalogs with an
explicit evidence source.
"""

from __future__ import annotations

from enum import IntEnum

NEGATIVE_RESPONSE_SID = 0x7F
POSITIVE_RESPONSE_OFFSET = 0x40
SUPPRESS_POSITIVE_RESPONSE = 0x80


class ServiceId(IntEnum):
    DIAGNOSTIC_SESSION_CONTROL = 0x10
    ECU_RESET = 0x11
    CLEAR_DIAGNOSTIC_INFORMATION = 0x14
    READ_DTC_INFORMATION = 0x19
    READ_DATA_BY_IDENTIFIER = 0x22
    READ_MEMORY_BY_ADDRESS = 0x23
    SECURITY_ACCESS = 0x27
    COMMUNICATION_CONTROL = 0x28
    WRITE_DATA_BY_IDENTIFIER = 0x2E
    ROUTINE_CONTROL = 0x31
    REQUEST_DOWNLOAD = 0x34
    REQUEST_UPLOAD = 0x35
    TRANSFER_DATA = 0x36
    REQUEST_TRANSFER_EXIT = 0x37
    TESTER_PRESENT = 0x3E


class Nrc(IntEnum):
    GENERAL_REJECT = 0x10
    SERVICE_NOT_SUPPORTED = 0x11
    SUB_FUNCTION_NOT_SUPPORTED = 0x12
    INCORRECT_MESSAGE_LENGTH_OR_INVALID_FORMAT = 0x13
    RESPONSE_TOO_LONG = 0x14
    BUSY_REPEAT_REQUEST = 0x21
    CONDITIONS_NOT_CORRECT = 0x22
    REQUEST_SEQUENCE_ERROR = 0x24
    NO_RESPONSE_FROM_SUBNET_COMPONENT = 0x25
    FAILURE_PREVENTS_EXECUTION = 0x26
    REQUEST_OUT_OF_RANGE = 0x31
    SECURITY_ACCESS_DENIED = 0x33
    AUTHENTICATION_REQUIRED = 0x34
    INVALID_KEY = 0x35
    EXCEEDED_NUMBER_OF_ATTEMPTS = 0x36
    REQUIRED_TIME_DELAY_NOT_EXPIRED = 0x37
    UPLOAD_DOWNLOAD_NOT_ACCEPTED = 0x70
    TRANSFER_DATA_SUSPENDED = 0x71
    GENERAL_PROGRAMMING_FAILURE = 0x72
    WRONG_BLOCK_SEQUENCE_COUNTER = 0x73
    RESPONSE_PENDING = 0x78
    SUB_FUNCTION_NOT_SUPPORTED_IN_ACTIVE_SESSION = 0x7E
    SERVICE_NOT_SUPPORTED_IN_ACTIVE_SESSION = 0x7F
    VOLTAGE_TOO_HIGH = 0x92
    VOLTAGE_TOO_LOW = 0x93


def nrc_name(code: int) -> str:
    try:
        return Nrc(code).name.lower()
    except ValueError:
        if 0x38 <= code <= 0x4F:
            return "reserved_by_extended_data_link_security"
        if 0x94 <= code <= 0xFE:
            return "reserved_or_manufacturer_specific"
        return "unknown"


class DiagnosticSessionType(IntEnum):
    DEFAULT = 0x01
    PROGRAMMING = 0x02
    EXTENDED = 0x03
    SAFETY_SYSTEM = 0x04


class ResetType(IntEnum):
    HARD = 0x01
    KEY_OFF_ON = 0x02
    SOFT = 0x03


class DtcReportType(IntEnum):
    NUMBER_OF_DTC_BY_STATUS_MASK = 0x01
    DTC_BY_STATUS_MASK = 0x02
    DTC_SNAPSHOT_IDENTIFICATION = 0x03
    DTC_SNAPSHOT_RECORD_BY_DTC_NUMBER = 0x04
    DTC_EXT_DATA_RECORD_BY_DTC_NUMBER = 0x06
    NUMBER_OF_DTC_BY_SEVERITY_MASK = 0x07
    DTC_BY_SEVERITY_MASK_RECORD = 0x08
    SUPPORTED_DTC = 0x0A


class RoutineControlType(IntEnum):
    START = 0x01
    STOP = 0x02
    REQUEST_RESULTS = 0x03


class CommunicationControlType(IntEnum):
    ENABLE_RX_AND_TX = 0x00
    ENABLE_RX_DISABLE_TX = 0x01
    DISABLE_RX_ENABLE_TX = 0x02
    DISABLE_RX_AND_TX = 0x03


class StandardDid(IntEnum):
    """Identification DIDs defined in ISO 14229-1 Annex C (0xF180-0xF19F)."""

    BOOT_SOFTWARE_IDENTIFICATION = 0xF180
    APPLICATION_SOFTWARE_IDENTIFICATION = 0xF181
    APPLICATION_DATA_IDENTIFICATION = 0xF182
    ACTIVE_DIAGNOSTIC_SESSION = 0xF186
    VEHICLE_MANUFACTURER_SPARE_PART_NUMBER = 0xF187
    VEHICLE_MANUFACTURER_ECU_SOFTWARE_NUMBER = 0xF188
    VEHICLE_MANUFACTURER_ECU_SOFTWARE_VERSION_NUMBER = 0xF189
    SYSTEM_SUPPLIER_IDENTIFIER = 0xF18A
    ECU_MANUFACTURING_DATE = 0xF18B
    ECU_SERIAL_NUMBER = 0xF18C
    VIN = 0xF190
    VEHICLE_MANUFACTURER_ECU_HARDWARE_NUMBER = 0xF191
    SYSTEM_SUPPLIER_ECU_HARDWARE_NUMBER = 0xF192
    SYSTEM_SUPPLIER_ECU_HARDWARE_VERSION_NUMBER = 0xF193
    SYSTEM_SUPPLIER_ECU_SOFTWARE_NUMBER = 0xF194
    SYSTEM_SUPPLIER_ECU_SOFTWARE_VERSION_NUMBER = 0xF195
    EXHAUST_REGULATION_OR_TYPE_APPROVAL_NUMBER = 0xF196
    SYSTEM_NAME_OR_ENGINE_TYPE = 0xF197
    REPAIR_SHOP_CODE_OR_TESTER_SERIAL_NUMBER = 0xF198
    PROGRAMMING_DATE = 0xF199
    ODX_FILE = 0xF19E


# Status bits of the DTC status byte (ISO 14229-1 D.2)
DTC_STATUS_TEST_FAILED = 0x01
DTC_STATUS_TEST_FAILED_THIS_OPERATION_CYCLE = 0x02
DTC_STATUS_PENDING = 0x04
DTC_STATUS_CONFIRMED = 0x08
DTC_STATUS_TEST_NOT_COMPLETED_SINCE_LAST_CLEAR = 0x10
DTC_STATUS_TEST_FAILED_SINCE_LAST_CLEAR = 0x20
DTC_STATUS_TEST_NOT_COMPLETED_THIS_OPERATION_CYCLE = 0x40
DTC_STATUS_WARNING_INDICATOR_REQUESTED = 0x80

# DTC severity bits (ISO 14229-1 D.3)
DTC_SEVERITY_MAINTENANCE_ONLY = 0x20
DTC_SEVERITY_CHECK_AT_NEXT_HALT = 0x40
DTC_SEVERITY_CHECK_IMMEDIATELY = 0x80

ALL_DTC_GROUPS = 0xFFFFFF
